spring.application.name=ecommerce-springboot

# 1. Database Connection URL
# Replace 'db_name' with your actual schema name
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Shoplify_db;encrypt=true;trustServerCertificate=true

# 2. Database Credentials
spring.datasource.username=sa
spring.datasource.password=StrongPassword123!

# 3. Hibernate / JPA Properties
# 'update' will automatically create/update tables based on your @Entity classes
spring.jpa.hibernate.ddl-auto=create

# Show the SQL queries in the console (great for debugging)
spring.jpa.show-sql=false

logging.level.root=warn
spring.main.banner-mode=off

# Choose the MS-SQL dialect (helps Hibernate optimize queries)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# File Upload Limit
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.max-file-size=10MB

file.upload.dir=./uploads